[package]
name = "fleascope-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "fleascope_rs"
path = "src/lib.rs"

[dependencies]
serialport = "4.0"
log = "0.4"
thiserror = "1.0"
polars = { version = "0.45", features = ["lazy", "csv", "strings"] }
chrono = { version = "0.4", features = ["serde"] }
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
env_logger = "0.10"
